dict_for_translit = {'а': 'a',
                     'б': 'b',
                     'в': 'v',
                     'г': 'g',
                     'д': 'd',
                     'е': 'e',
                     'ё': 'yo',
                     'ж': 'zh',
                     'з': 'z',
                     'и': 'i',
                     'й': 'j',
                     'к': 'k',
                     'л': 'l',
                     'м': 'm',
                     'н': 'n',
                     'о': 'o',
                     'п': 'p',
                     'р': 'r',
                     'с': 's',
                     'т': 't',
                     'у': 'u',
                     'ф': 'f',
                     'х': 'h',
                     'ц': 'ts',
                     'ч': 'ch',
                     'ш': 'sh',
                     'щ': 'sch',
                     'ъ': '',
                     'ы': 'y',
                     'ь': '',
                     'э': 'e',
                     'ю': 'yu',
                     'я': 'ya',
                     }


def translit(word):
    lst = []
    [lst.append(dict_for_translit[i]) for i in word]
    return ''.join(lst)